# Generated by Django 5.2.6 on 2025-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(choices=[('user', 'USER'), ('ai', 'AI'), ('admin', 'ADMIN')], max_length=10)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timeStamp'],
            },
        ),
    ]
