# Generated by Django 5.2.6 on 2025-11-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('admin', 'admin')], max_length=10),
        ),
    ]
