# Generated by Django 5.2.6 on 2025-11-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_file_message_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='filename',
            new_name='fileName',
        ),
    ]
