# Generated by Django 5.2.6 on 2025-11-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_attachments',
            new_name='file_attachment',
        ),
    ]
