# Generated by Django 5.2.6 on 2025-11-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_file_attachments_document_file_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner_id',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(max_length=512),
        ),
    ]
