# Generated by Django 5.2.6 on 2025-11-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_owner_id_alter_document_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='filename',
            new_name='file_name',
        ),
    ]
